/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type {RouteComponent} from "vue-router";
import type {LastLevelRouteKey, RouteLayout} from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
    base: BaseLayout,
    blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
    403: () => import("@/views/_builtin/403/index.vue"),
    404: () => import("@/views/_builtin/404/index.vue"),
    500: () => import("@/views/_builtin/500/index.vue"),
    "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
    login: () => import("@/views/_builtin/login/index.vue"),
    "route-view": () => import("@/views/_builtin/route-view/index.vue"),
    file: () => import("@/views/file/index.vue"),
    home: () => import("@/views/home/index.vue"),
    message_center: () => import("@/views/message_center/index.vue"),
    monitor_cache: () => import("@/views/monitor_cache/index.vue"),
    monitor_login_log: () => import("@/views/monitor_login_log/index.vue"),
    monitor_online: () => import("@/views/monitor_online/index.vue"),
    monitor_operation_log: () => import("@/views/monitor_operation_log/index.vue"),
    platform_tenant: () => import("@/views/platform_tenant/index.vue"),
    profile: () => import("@/views/profile/index.vue"),
    system_config: () => import("@/views/system_config/index.vue"),
    system_department: () => import("@/views/system_department/index.vue"),
    system_dictionary: () => import("@/views/system_dictionary/index.vue"),
    system_menu: () => import("@/views/system_menu/index.vue"),
    system_message: () => import("@/views/system_message/index.vue"),
    system_role: () => import("@/views/system_role/index.vue"),
    system_user: () => import("@/views/system_user/index.vue"),
};
